### ISSUE TITLE
Still accurate?

### ISSUE THREAD

**Issue by dcworldwide** [karthikiyengar/paypal-utils#1]
Just wondering if you are presently using this in production? I'm concerned about it's accuracy.

**Comment by karthikiyengar** [comment]
Actually, no.

I considered it for a while, but it turns out that payouts with PayPal is actually a bitch, given their atrocious documentation and processes. 

I moved to using Stripe instead, and it's pretty straightforward to use and achieve the same things. 

That being said, I'll add a deprecated note on the Readme :-)

**Comment by dcworldwide** [comment]
Interesting insight. Appreciate your opinion. Are you talking specifically about stripe connect?

**Comment by karthikiyengar** [comment]
Yup, talking about Stripe Connect. You can choose to subsume the payment/payout costs or pass it on to your customers, with a bit of calculation and clever coding.
